// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Comment struct {
	ID       int64
	ReviewID int64
	UserID   string
	Comment  string
	Created  string
}

type Review struct {
	ID          int64
	UserID      string
	ReviewTitle string
	BookTitle   string
	Isbn        string
	Rating      int64
	Review      string
	IsDraft     int64
	Created     string
}

type User struct {
	ID       string
	Username string
	Created  string
}
