// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (review_id, user_id, comment) VALUES (?, ?, ?)
`

type CreateCommentParams struct {
	ReviewID int64
	UserID   string
	Comment  string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment, arg.ReviewID, arg.UserID, arg.Comment)
	return err
}

const createReview = `-- name: CreateReview :exec
INSERT INTO reviews (
    user_id,
    review_title,
    book_title,
    isbn,
    rating,
    review,
    is_draft
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateReviewParams struct {
	UserID      string
	ReviewTitle string
	BookTitle   string
	Isbn        string
	Rating      int64
	Review      string
	IsDraft     int64
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.ExecContext(ctx, createReview,
		arg.UserID,
		arg.ReviewTitle,
		arg.BookTitle,
		arg.Isbn,
		arg.Rating,
		arg.Review,
		arg.IsDraft,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username) VALUES (?, ?)
`

type CreateUserParams struct {
	ID       string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Username)
	return err
}

const getComments = `-- name: GetComments :many
SELECT comments.id, comments.review_id, comments.user_id, comments.comment, comments.created, users.username
FROM comments
INNER JOIN users ON comments.user_id = users.id
WHERE review_id = ?
ORDER BY comments.id
`

type GetCommentsRow struct {
	ID       int64
	ReviewID int64
	UserID   string
	Comment  string
	Created  string
	Username string
}

func (q *Queries) GetComments(ctx context.Context, reviewID int64) ([]GetCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getComments, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsRow
	for rows.Next() {
		var i GetCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.UserID,
			&i.Comment,
			&i.Created,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReview = `-- name: GetReview :one
SELECT reviews.id, reviews.user_id, reviews.review_title, reviews.book_title, reviews.isbn, reviews.rating, reviews.review, reviews.is_draft, reviews.created, users.username
FROM reviews
INNER JOIN users ON users.id = reviews.user_id
WHERE reviews.id = ?
`

type GetReviewRow struct {
	ID          int64
	UserID      string
	ReviewTitle string
	BookTitle   string
	Isbn        string
	Rating      int64
	Review      string
	IsDraft     int64
	Created     string
	Username    string
}

func (q *Queries) GetReview(ctx context.Context, id int64) (GetReviewRow, error) {
	row := q.db.QueryRowContext(ctx, getReview, id)
	var i GetReviewRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ReviewTitle,
		&i.BookTitle,
		&i.Isbn,
		&i.Rating,
		&i.Review,
		&i.IsDraft,
		&i.Created,
		&i.Username,
	)
	return i, err
}

const getReviews = `-- name: GetReviews :many
SELECT reviews.id, reviews.user_id, reviews.review_title, reviews.book_title, reviews.isbn, reviews.rating, reviews.review, reviews.is_draft, reviews.created, users.username
FROM reviews
INNER JOIN users ON users.id = reviews.user_id
ORDER BY reviews.id DESC
`

type GetReviewsRow struct {
	ID          int64
	UserID      string
	ReviewTitle string
	BookTitle   string
	Isbn        string
	Rating      int64
	Review      string
	IsDraft     int64
	Created     string
	Username    string
}

func (q *Queries) GetReviews(ctx context.Context) ([]GetReviewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getReviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewsRow
	for rows.Next() {
		var i GetReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReviewTitle,
			&i.BookTitle,
			&i.Isbn,
			&i.Rating,
			&i.Review,
			&i.IsDraft,
			&i.Created,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsername = `-- name: GetUsername :one
SELECT username FROM users WHERE id = ?
`

func (q *Queries) GetUsername(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUsername, id)
	var username string
	err := row.Scan(&username)
	return username, err
}
