version: '3.8'

services:
  nyheter-challenge:
    build: ./chall
    ports:
      - "3000:3000"
    networks:
      - news_network

  nyheter-db:
    build: ./mariadb
    networks:
      - news_network

networks:
  news_network:
    driver: bridge

volumes:
  db_data:
