/* checker.c — ROM Bank 1 (BANKED): WRAM decrypt engine + sequence checker.
 *
 * Self-modifying code overview:
 *   The SM83 bytecode template (in wram_template.h, auto-generated by gen_flag.py)
 *   is an unrolled XOR-decrypt routine with FLAG_LEN placeholder key bytes (0x00).
 *   On each sequence check, the template is copied to WRAM ($C100) and the
 *   placeholder bytes are overwritten with keys derived from the player's last
 *   SEQ_LEN moves.  The WRAM routine is then called as a function pointer —
 *   it decrypts the encrypted flag into the output buffer.
 *
 *   Key derivation: derive_key(step, dir) = (((dir+1)*0x5D) ^ (step*0x37) ^ 0xAB) & 0xFF
 *     where dir: 0=N, 1=E, 2=S, 3=W
 *
 *   Flag byte i uses key[i % SEQ_LEN].  The key for step s covers flag bytes
 *   s, s+SEQ_LEN, s+2*SEQ_LEN, ...  up to FLAG_LEN.
 *
 * Uniqueness guarantee (check_sequence):
 *   1. FLAG_MAGIC pre-filter: first FLAG_MAGIC_LEN decrypted bytes match.
 *   2. Bijective fingerprint: base4_encode(input_seq) matches STORED_FP_*.
 *      Since base4_encode is a bijection, only the correct sequence passes.
 */

#pragma bank 1

#include <stdint.h>
#include "../include/common.h"
#include "../include/checker.h"
#include "../include/flag_access.h"
#include "../include/wram_template.h"   /* AUTO-GENERATED: wram_template[] */

/* ── Internal key derivation ─────────────────────────────────────────────── */
static uint8_t derive_key(uint8_t step, uint8_t dir) {
    return (uint8_t)(((uint8_t)((dir + 1U) * 0x5DU)) ^
                     ((uint8_t)(step * 0x37U))         ^
                     0xABU);
}

/* ── Public BANKED API ───────────────────────────────────────────────────── */

void init_wram(void) BANKED {
    uint8_t i;
    uint8_t *dst = (uint8_t *)WRAM_ROUTINE_ADDR;

    for(i = 0; i < WRAM_ROUTINE_SIZE; i++)
        dst[i] = wram_template[i];

    /* Pull encrypted flag bytes from ROM bank 2 into WRAM buffer. */
    get_flag_data((uint8_t *)WRAM_ENC_FLAG_ADDR);
}

void reset_wram(void) BANKED {
    uint8_t i;
    uint8_t *dst = (uint8_t *)WRAM_ROUTINE_ADDR;
    for(i = 0; i < WRAM_ROUTINE_SIZE; i++)
        dst[i] = wram_template[i];
}

void patch_wram(uint8_t step, uint8_t dir) BANKED {
    uint8_t key  = derive_key(step, dir);
    uint8_t *base = (uint8_t *)WRAM_ROUTINE_ADDR;
    uint8_t pos  = step;
    /* Key for step s covers flag bytes s, s+SEQ_LEN, s+2*SEQ_LEN, ...
     * Key byte for flag byte i lives at base[6 + i*5 + 2]
     * (preamble=6 bytes; each block is 2A EE XX 12 13, XX at offset +2). */
    while(pos < FLAG_LEN) {
        base[6U + (uint8_t)(pos * 5U) + 2U] = key;
        pos = (uint8_t)(pos + SEQ_LEN);
    }
}

uint8_t check_sequence(uint8_t *move_history, uint8_t head) BANKED {
    uint8_t s;
    uint8_t i;
    uint8_t *out;
    uint32_t fp;
    uint8_t obfusc;

    /* Re-copy clean template (zeroes all XOR key bytes) */
    reset_wram();

    /* Patch all SEQ_LEN key slots from the ring buffer */
    for(s = 0; s < SEQ_LEN; s++) {
        uint8_t dir = move_history[(uint8_t)(head + s) % SEQ_LEN];
        patch_wram(s, dir);
    }

    /* Execute the patched WRAM routine */
    {
        typedef void (*wram_fn_t)(void);
        ((wram_fn_t)WRAM_ROUTINE_ADDR)();
    }

    out = (uint8_t *)WRAM_DEC_FLAG_ADDR;

    /* 1. FLAG_MAGIC pre-filter: fast check before fingerprint */
    for(i = 0; i < FLAG_MAGIC_LEN; i++) {
        if(out[i] != FLAG_MAGIC[i]) return 0;
    }

    /* 2. Bijective fingerprint check — guaranteed exactly one sequence matches.
     *    fp = base4_encode(input_seq): seq[s] packed as 2-bit fields.
     *    STORED_FP_* = (base4_encode(correct_seq) byte i) ^ obfusc.
     *    Since base4_encode is a bijection, any different sequence produces
     *    a different fp and will fail this check. */
    fp = 0U;
    for(s = 0; s < SEQ_LEN; s++) {
        fp |= ((uint32_t)move_history[(uint8_t)(head + s) % SEQ_LEN]) << (2U * s);
    }
    obfusc = (uint8_t)(ENC_FLAG_FIRST ^ ENC_FLAG_LAST);

    return (uint8_t)(
        (((uint8_t)(fp        & 0xFFU)) ^ obfusc) == STORED_FP_0 &&
        (((uint8_t)((fp >> 8) & 0xFFU)) ^ obfusc) == STORED_FP_1 &&
        (((uint8_t)((fp >>16) & 0xFFU)) ^ obfusc) == STORED_FP_2 &&
        (((uint8_t)((fp >>24) & 0xFFU)) ^ obfusc) == STORED_FP_3
    );
}
