#ifndef COMMON_H
#define COMMON_H

#include <gb/gb.h>
#include <stdint.h>

/* ── Generated constants (FLAG_LEN, SEQ_LEN, WRAM layout, fingerprint) ──────
 * These are defined in include/flag_data.h, generated by gen_flag.py.
 * Do NOT define them here.
 * ─────────────────────────────────────────────────────────────────────────── */
#include "../include/flag_data.h"

/* Direction encoding (must match gen_flag.py) */
#define DIR_N  0
#define DIR_E  1
#define DIR_S  2
#define DIR_W  3

/* ── Tile IDs ────────────────────────────────────────────────────────────── */
#define TILE_FLOOR   0
#define TILE_WALL    1
#define TILE_PILLAR  2
#define TILE_CHEST   3

/* ── Map dimensions (Game Boy native = 160×144 px = 20×18 tiles) ─────────── */
#define MAP_W  20
#define MAP_H  18

/* ── Player spawn position (tile coordinates) ────────────────────────────── */
#define PLAYER_START_X  9
#define PLAYER_START_Y  8

/* ── Sprite hardware offset (OAM positions are offset by 8,16) ───────────── */
#define SPR_OFS_X  8
#define SPR_OFS_Y  16

/* ── Game states ─────────────────────────────────────────────────────────── */
#define STATE_PLAY  0
#define STATE_WIN   1

#endif /* COMMON_H */
