/* AUTO-GENERATED by gen_flag.py — DO NOT EDIT */
/* Re-generate with: python gen_flag.py --flag "..." --seq "..." */
#ifndef FLAG_DATA_H
#define FLAG_DATA_H

/* ── Sizes ────────────────────────────────────────────────────────────── */
#define FLAG_LEN         26
#define SEQ_LEN          10
#define FLAG_MAGIC_LEN   4

/* ── WRAM layout ──────────────────────────────────────────────────────── */
#define WRAM_ROUTINE_ADDR    0xC100
#define WRAM_ROUTINE_SIZE    137
#define WRAM_ENC_FLAG_ADDR   0xC190
#define WRAM_DEC_FLAG_ADDR   0xC1AA

/* ── Encrypted flag — extern declaration (definition in enc_flag_data.h) */
extern const uint8_t ENC_FLAG[26];

/* First and last encrypted bytes — used for fingerprint obfuscation */
#define ENC_FLAG_FIRST  0xA5
#define ENC_FLAG_LAST   0x98

/* ── Fingerprint verification constants (ROM bank 1) ─────────────────── *
 * Stored as: STORED_FP_i = (base4_encode(correct_seq) byte i) ^ (ENC_FLAG_FIRST ^ ENC_FLAG_LAST)
 * The check_sequence() function computes base4_encode(input_seq), applies the
 * same obfuscation, and compares to these values.  The bijection guarantees
 * exactly one sequence produces a match.
 */
#define STORED_FP_0     0x8D
#define STORED_FP_1     0xAC
#define STORED_FP_2     0x3D
#define STORED_FP_3     0x3D

/* ── Flag magic prefix (ROM bank 1) — plaintext pre-filter ───────────── *
 * First 4 bytes of the flag stored in bank 1 as a fast pre-check
 * before the more expensive fingerprint comparison.  Intentionally visible to
 * a reverser as a clue, but knowing the prefix does not reveal the sequence.
 */
static const uint8_t FLAG_MAGIC[FLAG_MAGIC_LEN] = {
    0x53, 0x43, 0x53, 0x43
};

#endif /* FLAG_DATA_H */
