from ubuntu:22.04

# Install the necessary packages
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    gcc-aarch64-linux-gnu \
    qemu-user \
    gdb \
    gdbserver \
    tmux \
    gdb-multiarch \
    git \
    sl


RUN pip install pwntools

RUN git clone https://github.com/pwndbg/pwndbg
RUN bash -c "cd pwndbg ; ./setup.sh"

RUN mkdir /build
RUN echo 3
COPY bin /build/bin
COPY web_serve /build/web_serve
COPY Makefile /build

# Set the working directory
WORKDIR /build
RUN make build-bin
COPY solve.py /build/solve.py

# Set the entrypoint
ENTRYPOINT ["/bin/bash", "-c", "export QEMU_LD_PREFIX=\"/usr/aarch64-linux-gnu/\"; tmux"]
