from string import Template

story_template = Template('''Rain lashed against the leaded glass windows of the Café de la Cryptographie, turning the vibrant city lights outside into a beautiful, blurred smear of bruised purples and electric golds. Inside, the air was thick with the rich, intoxicating scent of freshly ground espresso and old, rain-dampened wool. Alice sat across from Bob in a velvet booth the color of midnight, her heart fluttering like a captive bird against her ribs. They were agonizingly close, their knees brushing beneath the scarred wooden table, yet the crowded room kept them miles apart. Just one table over, a woman in a sharp crimson trench coat was sipping a bitter macchiato, her ears visibly straining to catch the delicate, fragile thread of their conversation. They needed to whisper their deepest confessions, to synchronize their hearts away from the prying eyes and ears of the world, but they could only speak in the open.

Bob leaned forward, his dark eyes catching the warm, flickering amber of the candlelight. "We need a sanctuary," he murmured, his voice a low, mesmerizing baritone that sent a shiver down Alice's spine. "Let us build a foundation, a shared modulus to define the boundaries of our own private universe. Let us use the prime $prime, my love." Alice felt a blush creep up her neck, her gaze dropping to the porcelain rim of her teacup. "$prime is perfect," she breathed, a soft smile playing on her lips. "A strong, unbreakable prime to hold us together. But a universe needs a spark to set it in motion. Let our generator be $generator, to ignite the quiet space between us."

With the foundation of their universe laid bare for anyone to hear, the true dance of their hearts began. Beneath the table, out of sight, Alice retreated into the quiet sanctum of her mind. She held onto a fiercely guarded secret number, a private key locked safely away in her soul. Mentally, she took their shared spark, the $generator, and raised it to the power of her secret devotion, wrapping the result gently within the protective mathematical embrace of their $prime-boundary world. The mathematics of her love distilled down to a single, elegant figure. She reached across the table, her fingertips lightly brushing his knuckles, and slid a crumpled paper napkin toward him. "Then take this," she whispered, her eyes locking onto his with an intensity that made the surrounding cafe melt away. "$alice_pk. A symbol derived from the depths of my own quiet longing, offered only to you."

Bob’s breath hitched as he stared at the handwritten number, the ink slightly feathered by the damp air. He knew $alice_pk was a piece of her soul, transformed and sent across the perilous void of the room. Now, it was his turn. In the fortress of his own heart, he harbored a turbulent, unspoken secret number of his own. He wouldn't dare breathe it aloud. Instead, he took their shared spark of $generator, elevated it by his burning secret, and let the modulus of $prime bring it back down to earth. He leaned in so close that Alice could smell the petrichor and sandalwood clinging to his jacket. "And for you, my reply," he murmured softly, his breath warm against the chill of the windowpane. "$bob_pk. The sum of all my affection, wrapped in our shared reality."

As the woman in the crimson coat scribbled the meaningless numbers $alice_pk and $bob_pk into her notebook, utterly defeated by their mundane appearance without the hidden keys, Alice and Bob simply sat in profound, electric silence. Alice took his $bob_pk, applying her secret to it within the bounds of $prime, while Bob took her $alice_pk, elevating it with his own hidden number. In an instant, the chaotic arithmetic settled. A new, identical number blossomed simultaneously in both of their minds, an invisible golden thread tying them together. They didn't need to say the final number out loud; speaking it would shatter the delicate, cryptographic magic they had woven. Instead, their eyes met, shining with the shared, unspoken knowledge of the secret key they had just forged. In a room full of strangers and shadows, they had finally found a way to be entirely, beautifully alone.''')

flag = b"SSM{4_t0k3n_0f_0ur_l0v3_<3}"
